version: "3"
services:
  web:
    container_name: iwell-deo
    image: iwell-deo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    command: iwell celery
    env_file:
      - .env
