version: "3.7"

x-defaults: &defaults
  image: iwell-deo
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  env_file:
    - .env
  depends_on:
    - redis

services:
  worker:
    <<: *defaults
    user: celeryuser
    command: iwell run worker
  cron:
    <<: *defaults
    user: celeryuser
    command: iwell run cron --loglevel=DEBUG
  monitor:
    <<: *defaults
    user: celeryuser
    command: iwell run monitor
    ports:
      - "5001:5001"
  redis:
    image: redis-deo
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
