version: "3.7"

x-defaults: &defaults
  image: driftwood/iwell:0.1.0
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  environment:
    - AWS_REGION
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - AWS_SECURITY_TOKEN

services:
  worker:
    <<: *defaults
    user: celeryuser
    command: iwell run worker
    # command: env
  # cron:
  #   <<: *defaults
  #   user: celeryuser
  #   command: iwell run cron --loglevel=DEBUG
