"""empty message

Revision ID: 20d38cfe7b17
Revises: 9b34279207eb
Create Date: 2019-10-22 13:13:42.301804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20d38cfe7b17"
down_revision = "9b34279207eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "run_tickets", "comments", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "run_tickets", "picture_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "run_tickets", "product_type", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "run_tickets", "product_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "run_tickets", "picture_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "run_tickets", "comments", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
