"""empty message

Revision ID: 7a5508ba53b2
Revises: ff97e8d15fde
Create Date: 2019-10-12 18:00:24.415594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5508ba53b2'
down_revision = 'ff97e8d15fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('field_unit', sa.String(), nullable=True),
    sa.Column('field_order', sa.Integer(), nullable=True),
    sa.Column('is_historic', sa.Boolean(), nullable=False),
    sa.Column('is_remembered', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_iwell', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_iwell', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='iwell'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields', schema='iwell')
    # ### end Alembic commands ###
