default_schedule: &default_schedule
  seconds: 15

default_aliases: &default_aliases
  created_at: iwell_created_at
  updated_at: iwell_updated_at


endpoints:
  users:
    model: api.models.User
    mappings:
      aliases:
        type: user_type
    exclude: []
    normalize: false
    path: /users
    version: v1
    tasks:
      sync:
        <<: *default_schedule
        # cron:
        #   minute: "*"
        #   hour:
        #   day_of_week:
        #   day_of_month:
        #   month_of_year:
  wells:
    model: api.models.Well
    path: /wells
    options:
      - since
    mappings:
      aliases:
        <<: *default_aliases
        alias: well_alias
        name: well_name
        type: well_type
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  tanks:
    model: api.models.Tank
    options:
      - since
    mappings:
      aliases:
        <<: *default_aliases
        name: tank_name
        type: tank_type
    exclude: []
    normalize: false
    path: /tanks
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  fields:
    model: api.models.Field
    path: /fields
    mappings:
      aliases:
        <<: *default_aliases
        name: field_name
        order: field_order
        type: field_type
        unit: field_unit
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  tank_readings:
    model: api.models.TankReading
    path: /tanks/{tank_id}/readings
    depends_on:
      tank_id: api.models.Tank.id
    mappings:
      aliases:
        <<: *default_aliases
        reading_time: reading_at
    exclude: []
    depends_on:
      tank_id: api.models.Tank.id
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  field_values:
    model: api.models.FieldValue
    path: /wells/{well_id}/fields/{field_id}/values
    options:
      - since
      - start
      - end
    depends_on:
      field_id: api.models.WellField.field_id
      well_id: api.models.WellField.well_id
    mappings:
      aliases:
        <<: *default_aliases
        reading_time: reading_at
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  meters:
    model: api.models.Meter
    path: /wells/{well_id}/meters
    options:
      - since
      - kind
    depends_on:
      well_id: api.models.Well.id
    mappings:
      aliases:
        <<: *default_aliases
        date: reading_at
        name: meter_name
        order: meter_order
        type: product_type
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  meter_readings:
    model: api.models.MeterReading
    path: /wells/{well_id}/meters/{meter_id}/readings
    options:
      - since
      - start
      - end
    depends_on:
      well_id: api.models.Meter.well_id
      meter_id: api.models.Meter.id
    mappings:
      aliases:
        <<: *default_aliases
        reading_time: reading_at
        reading: value
        previous_reading: previous_value
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  production:
    model: api.models.Production
    path: /wells/{well_id}/production
    options:
      - since
      - start
      - end
    depends_on:
      well_id: api.models.Well.id
    mappings:
      aliases:
        <<: *default_aliases
        production_time: produced_at
        date: reported_date
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  run_tickets:
    model: api.models.RunTicket
    path: /tanks/{tank_id}/readings/{reading_id}/run-tickets
    options:
      - since
    depends_on:
      tank_id: api.models.TankReading.tank_id
      reading_id: api.models.TankReading.id
    mappings:
      aliases:
        <<: *default_aliases
        date: ticket_date
        type: product_type
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  well_fields:
    model: api.models.WellField
    path: /wells/{well_id}/fields
    depends_on:
      well_id: api.models.Well.id
    mappings:
      aliases:
        <<: *default_aliases
        id: field_id
    exclude:
      - name
      - order
      - type
      - unit
      - is_required
      - is_historic
      - is_remembered
      - order
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  well_groups:
    model: api.models.WellGroup
    path: /well-groups
    mappings:
      aliases:
        <<: *default_aliases
        latest_production_time: group_latest_production_time
        name: group_name
    exclude:
      - wells.data
    normalize: true
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  well_group_wells:
    model: api.models.WellGroupWell
    path: /well-groups/{group_id}/wells
    depends_on:
      group_id: api.models.WellGroup.id
    mappings:
      aliases:
        <<: *default_aliases
        id: well_id
    exclude:
      - type
      - name
      - latest_production_time
      - is_active
      - alias
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  well_notes:
    model: api.models.WellNote
    path: /wells/{well_id}/notes
    depends_on:
      well_id: api.models.Well.id
    mappings:
      aliases:
        <<: *default_aliases
        note_time: noted_at
    exclude: []
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
  well_tanks:
    model: api.models.WellTank
    path: /wells/{well_id}/tanks
    depends_on:
      well_id: api.models.Well.id
    mappings:
      aliases:
        <<: *default_aliases
        id: tank_id
    exclude:
      - capacity
      - multiplier
      - name
      - type
    normalize: false
    version: v1
    tasks:
      sync:
        <<: *default_schedule
functions:
  since:
    alternatives: null
    example: "since=32342561"
    template: "since={value}"
