!!python/object/new:src.config.Config
dictitems:
  cached_at: 2019-01-10 13:37:43.902137
  client_id: KTDMpqhGyBMhnRDB
  client_secret: gYFRiXRtMN0fDYTDPUDYOk1RAbPz44Bu
  endpoints:
    field_values:
      aliases:
        created_at: created_iwell
        id: value_id
        updated_at: updated_iwell
      exclude: []
      keys: null
      last_failure: 2018-10-18 11:34:47.046800
      last_success: 2019-01-10 13:14:50.350627
      normalize: false
      path: /wells/{well_id}/fields/{field_id}/values
    fields:
      aliases:
        created_at: created_iwell
        id: field_id
        name: field_name
        order: field_order
        type: field_type
        unit: field_unit
        updated_at: updated_iwell
      exclude: []
      keys: null
      last_failure: null
      last_success: 2019-01-10 13:14:47.716076
      normalize: false
      path: /fields
    fields_by_well:
      aliases:
        created_at: created_iwell
        id: field_id
        name: field_name
        order: field_order
        type: field_type
        unit: field_unit
        updated_at: updated_iwell
      exclude: []
      keys: null
      last_failure: 2018-10-18 13:29:57.447666
      last_success: 2019-01-10 13:14:48.732180
      normalize: false
      path: /wells/{well_id}/fields
    meter_readings:
      aliases:
        created_at: created_iwell
        id: meter_reading_id
        updated_at: updated_iwell
      exclude: []
      keys: !!python/tuple
      - well_id
      - meter_id
      last_failure: 2018-10-18 11:03:54.492051
      last_success: 2019-01-10 13:14:44.688786
      normalize: false
      path: /wells/{well_id}/meters/{meter_id}/readings
    meters:
      aliases:
        created_at: created_iwell
        date: reading_date
        id: meter_id
        name: meter_name
        order: meter_order
        type: product_type
        updated_at: updated_iwell
      exclude: []
      keys: well_id
      last_failure: 2018-10-18 13:29:55.186960
      last_success: 2019-01-10 13:14:42.459598
      normalize: false
      path: /wells/{well_id}/meters
    production:
      aliases:
        created_at: created_iwell
        id: production_id
        production_time: prod_datetime
        updated_at: updated_iwell
      exclude:
      - date
      keys: well_id
      last_failure: 2018-10-18 14:29:14.030966
      last_success: 2019-01-10 13:37:43.902137
      normalize: false
      path: /wells/{well_id}/production
    run_tickets:
      aliases:
        created_at: created_iwell
        date: reading_date
        id: run_ticket_id
        type: product_type
        updated_at: updated_iwell
      exclude: []
      keys: !!python/tuple
      - tank_id
      - reading_id
      - run_ticket_id
      last_failure: null
      last_success: 2019-01-10 13:18:43.078318
      normalize: false
      path: /tanks/{tank_id}/readings/{reading_id}/run-tickets
    tank_readings:
      aliases:
        created_at: created_iwell
        id: reading_id
        updated_at: updated_iwell
      exclude: []
      keys: tank_id
      last_failure: 2018-10-18 11:59:44.620958
      last_success: 2019-01-10 13:15:09.143501
      normalize: false
      path: /tanks/{tank_id}/readings
    tanks:
      aliases:
        created_at: created_iwell
        id: tank_id
        name: tank_name
        type: tank_type
        updated_at: updated_iwell
      exclude: []
      keys: null
      last_failure: null
      last_success: 2019-01-10 13:15:05.185403
      normalize: false
      path: /tanks
    well_field_values:
      aliases:
        created_at: created_iwell
        id: value_id
        updated_at: updated_iwell
      exclude: []
      keys: !!python/tuple
      - well_id
      - field_id
      last_failure: null
      last_success: 2018-10-09 22:14:16.190385
      normalize: false
      path: /wells/{well_id}/fields/{field_id}/values
    well_fields:
      aliases:
        created_at: created_iwell
        id: field_id
        name: field_name
        order: field_order
        type: field_type
        unit: field_unit
        updated_at: updated_iwell
      exclude: []
      keys: well_id
      last_failure: null
      last_success: 2018-10-09 22:14:16.190886
      normalize: false
      path: /wells/{well_id}/fields
    well_group_wells:
      aliases:
        created_at: created_iwell
        id: well_id
        updated_at: updated_iwell
      exclude:
      - type
      - name
      - latest_production_time
      - is_active
      - alias
      keys: group_id
      last_failure: null
      last_success: 2019-01-10 13:18:51.672631
      normalize: false
      path: /well-groups/{group_id}/wells
    well_groups:
      aliases:
        created_at: created_iwell
        id: group_id
        latest_production_time: group_latest_production_time
        name: group_name
        updated_at: updated_iwell
      exclude:
      - wells.data
      keys: null
      last_failure: null
      last_success: 2019-01-10 13:18:51.461536
      normalize: true
      path: /well-groups
    well_notes:
      aliases:
        created_at: created_iwell
        id: note_id
        updated_at: updated_iwell
      exclude: []
      keys: well_id
      last_failure: 2018-10-18 13:30:28.855766
      last_success: 2019-01-10 13:18:50.079841
      normalize: false
      path: /wells/{well_id}/notes
    well_tanks:
      aliases:
        created_at: created_iwell
        id: tank_id
        updated_at: updated_iwell
      exclude:
      - capacity
      - multiplier
      - name
      - type
      keys: well_id
      last_failure: 2018-10-18 13:30:03.591703
      last_success: 2019-01-10 13:15:13.130124
      normalize: false
      path: /wells/{well_id}/tanks
    wells:
      aliases:
        alias: well_alias
        created_at: created_iwell
        id: well_id
        name: well_name
        type: well_type
        updated_at: updated_iwell
      exclude: []
      keys: null
      last_failure: 2019-01-10 12:55:31.307823
      last_success: 2019-01-10 13:14:39.398590
      normalize: false
      path: /wells
  password: 7haYrAaFqTwS
  token: zEblfN8wOf6cam4NlhFqlYEpyuOm3cUsjPuQJOoV
  token_expiration: 2019-01-13 16:33:02.011551
  token_path: /oauth2/access-token
  url: https://api.iwell.info/v1
  username: data@driftwoodenergy.com
state:
  filename: ./config/config.yaml
