version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(name)s - %(levelname)s - %(message)s'
    detail:
        format: '[%(asctime)s - %(filename)s:%(lineno)s - %(funcName)s()] %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detail
        filename: log/{project_dir_name}.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    main:
        level: INFO
        handlers: [console, debug_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, debug_file_handler]